export const meshOptions:any = {
	"contour":{
		"contour":{"image":{"registry":"docker.io","repository":"projectcontour/contour","tag":"v1.18.0"}},
		"enabled":false,
		"sidecar":{"image":{"registry":"docker.io","repository":"envoyproxy/envoy-alpine","tag":"v1.19.3"}},
	},
	"osm":{
		"caBundleSecretName":"osm-ca-bundle",
		"certificateProvider":{
			"certKeyBitSize":2048,
			"kind":"tresor",
			"serviceCertValidityDuration":"24h"
		},
		"certmanager":{
			"issuerGroup":"cert-manager.io",
			"issuerKind":"Issuer",
			"issuerName":"osm-ca",
		},
		"configResyncInterval":"0s",
		"controlPlaneTolerations":[],
		"controllerLogLevel":"info",
		"curlImage":"curlimages/curl",
		"deployGrafana":false,
		"deployJaeger":false,
		"deployPrometheus":true,
		"enableDebugServer":false,
		"enableEgress":false,
		"enableFluentbit":false,
		"enablePermissiveTrafficPolicy":false,
		"enablePrivilegedInitContainer":false,
		"enableReconciler":false,
		"enforceSingleMesh":true,
		"featureFlags":{
			"enableAsyncProxyServiceMapping":false,
			"enableEgressPolicy":true,
			"enableIngressBackendPolicy":true,
			"enableMulticlusterMode":false,
			"enableRetryPolicy":false,
			"enableSidecarActiveHealthChecks":false,
			"enableSnapshotCacheMode":false,
			"enableWASMStats":false,
		},
		"fluentBit":{
			"enableProxySupport":false,
			"httpProxy":"",
			"httpsProxy":"",
			"name":"fluentbit-logger",
			"outputPlugin":"stdout",
			"primaryKey":"",
			"pullPolicy":"IfNotPresent",
			"registry":"fluent",
			"tag":"1.6.4",
			"workspaceId":"",
		},
		"grafana":{
			"enableRemoteRendering":false,
			"image":"grafana/grafana:8.2.2",
			"port":3000,
			"rendererImage":"grafana/grafana-image-renderer:3.2.1",
		},
		"image":{
			"digest":{
				"osmBootstrap":"",
				"osmCRDs":"",
				"osmController":"",
				"osmHealthcheck":"",
				"osmInjector":"",
				"osmPreinstall":"",
				"osmSidecarInit":""
			},
			"name":{
				"osmBootstrap":"osm-edge-bootstrap",
				"osmCRDs":"osm-edge-crds",
				"osmController":"osm-edge-controller",
				"osmHealthcheck":"osm-edge-healthcheck",
				"osmInjector":"osm-edge-injector",
				"osmPreinstall":"osm-edge-preinstall",
				"osmSidecarInit":"osm-edge-sidecar-init",
			},
			"pullPolicy":"IfNotPresent",
			"registry":"flomesh",
			"tag":"latest",
		},
		"imagePullSecrets":[],
		"inboundPortExclusionList":[],
		"injector":{
			"autoScale":{
				"cpu":{
					"targetAverageUtilization":80
				},
				"enable":false,
				"maxReplicas":5,
				"memory":{
					"targetAverageUtilization":80
				},
				"minReplicas":1
			},
			"enablePodDisruptionBudget":false,
			"podLabels":{},
			"replicaCount":1,
			"resource":{"limits":{"cpu":"0.5","memory":"64M"},"requests":{"cpu":"0.3","memory":"64M"}},
			"webhookTimeoutSeconds":20,
		},
		"maxDataPlaneConnections":0,
		"meshName":"osm",
		"multicluster":{"gatewayLogLevel":"error"},
		"nodeSelector":{
			"arch":"amd64",
			"os":"linux",
		},
		"osmBootstrap":{
			"podLabels":{},
			"replicaCount":1,
			"resource":{"limits":{"cpu":"0.5","memory":"128M"},"requests":{"cpu":"0.3","memory":"128M"}},
		},
		"osmController":{
			"autoScale":{"cpu":{"targetAverageUtilization":80},"enable":false,"maxReplicas":5,"memory":{"targetAverageUtilization":80},"minReplicas":1},
			"enablePodDisruptionBudget":false,
			"podLabels":{},
			"replicaCount":1,
			"resource":{"limits":{"cpu":"1.5","memory":"1G"},"requests":{"cpu":"0.5","memory":"128M"}},
		},
		"osmNamespace":"",
		"outboundIPRangeExclusionList":[],
		"outboundIPRangeInclusionList":[],
		"outboundPortExclusionList":[],
		"prometheus":{
			"image":"prom/prometheus:v2.18.1",
			"port":7070,
			"resources":{"limits":{"cpu":"1","memory":"2G"},"requests":{"cpu":"0.5","memory":"512M"}},
			"retention":{"time":"15d"},
		},
		"sidecarClass":"pipy",
		"sidecarDrivers":[{"sidecarDisabledMTLS":false,"sidecarImage":"flomesh/pipy-nightly:latest","sidecarName":"pipy","sidecarWindowsImage":"flomesh/pipy-windows-nightly:latest"},{"sidecarImage":"envoyproxy/envoy:v1.19.3","sidecarName":"envoy","sidecarWindowsImage":"envoyproxy/envoy-windows:latest"}],
		"sidecarImage":"flomesh/pipy-nightly:latest",
		"sidecarLogLevel":"error",
		"sidecarWindowsImage":"flomesh/pipy-windows-nightly:latest",
		"tracing":{
			"address":"",
			"enable":false,
			"endpoint":"/api/v2/spans",
			"image":"jaegertracing/all-in-one",
			"port":9411,
		},
		"validatorWebhook":{
			"webhookConfigurationName":"",
		},
		"vault":{
			"host":"",
			"protocol":"http",
			"role":"openservicemesh",
			"token":"",
		},
		"webhookConfigNamePrefix":"osm-webhook",
	},
	"smi":{
		"validateTrafficTarget":true
	}
}